// Mi Grow progress data. Generated by index.html -> "Exportar progreso.js". Commit this file.
window.GROW_DATA = {
  "version": 1,
  "updatedAt": "2026-09-28T16:15:54.357Z",
  "period": {
    "start": "2026-09-01",
    "end": "2027-02-28"
  },
  "segments": [
    {
      "id": "s1",
      "name": "Análisis / requerimientos"
    },
    {
      "id": "s2",
      "name": "Diseño"
    },
    {
      "id": "s3",
      "name": "Implementación"
    },
    {
      "id": "s4",
      "name": "Pruebas"
    },
    {
      "id": "s5",
      "name": "Despliegue y validación"
    }
  ],
  "goals": {
    "o1": {
      "checks": {
        "metodo": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o1-ai-first/comparacion-3x.md#método",
          "note": "Tradicional = Duración final en Jira SIGE (Portal del Colaborador, 2025). IA = tiempo activo de sesiones Claude por rama. Falta visto bueno del líder sobre comparabilidad"
        },
        "analisis": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o1-ai-first/uso-habitual-ia.md#análisis-de-código",
          "note": "141 propuestas OpenSpec generadas con IA antes de implementar"
        },
        "desarrollo": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o1-ai-first/uso-habitual-ia.md#desarrollo",
          "note": "89 PRs y 334 commits hechos con Claude Code; 359 sesiones"
        },
        "debugging": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o1-ai-first/uso-habitual-ia.md#debugging",
          "note": "Ej. #443, #457, #477, #489"
        },
        "pruebas": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o1-ai-first/uso-habitual-ia.md#pruebas",
          "note": "Agente qa-engineer; tests generados con cada feature; CI con unit, DB y smoke"
        },
        "docs": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o1-ai-first/uso-habitual-ia.md#documentación",
          "note": "18 specs OpenSpec, CHANGELOG y PRs documentados"
        },
        "control": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o1-ai-first/uso-habitual-ia.md#control-y-validación-técnica",
          "note": "CI 75/78 PRs en verde + agentes code-reviewer/security. Débil: casi sin revisión humana en GitHub"
        }
      },
      "rows": [
        {
          "id": "p342",
          "caso": "Pantalla nueva con formulario: AP #342 vs SIGE-87 (24 h)",
          "fecha": "2026-09-02",
          "actividad": "Desarrollo",
          "hTrad": "24",
          "hIA": "3.1",
          "validacion": "CI 11/11 verde · 9 archivos de test · base SIGE-87 Duración final",
          "validado": true,
          "evidencia": "https://github.com/CHidalgo29/AgentPlatform/pull/342"
        },
        {
          "id": "p386",
          "caso": "Pantalla que consume API (+ backend): AP #386 vs SIGE-126 (24 h)",
          "fecha": "2026-09-09",
          "actividad": "Desarrollo",
          "hTrad": "24",
          "hIA": "5.9",
          "validacion": "CI 11/11 verde · 19 archivos de test · base SIGE-126 Duración final",
          "validado": true,
          "evidencia": "https://github.com/CHidalgo29/AgentPlatform/pull/386"
        },
        {
          "id": "p491",
          "caso": "Actualización de UI en varias pantallas: AP #491 vs SIGE-355 (32 h)",
          "fecha": "2026-09-23",
          "actividad": "Desarrollo",
          "hTrad": "32",
          "hIA": "5.4",
          "validacion": "CI 11/11 verde · 33 archivos de test · base SIGE-355 Duración final",
          "validado": true,
          "evidencia": "https://github.com/CHidalgo29/AgentPlatform/pull/491"
        },
        {
          "id": "c392",
          "caso": "Candidato extra: Duplicar agente desde catálogo y detalle (#392)",
          "fecha": "2026-09-09",
          "actividad": "Desarrollo",
          "hTrad": "",
          "hIA": "3.3",
          "validacion": "CI 11/11 verde · 31 archivos de test · OpenSpec duplicate-agent-from-catalog",
          "validado": true,
          "evidencia": "https://github.com/CHidalgo29/AgentPlatform/pull/392"
        },
        {
          "id": "c437",
          "caso": "Candidato extra: Flujo de retiro de agentes desplegados (#437, #440)",
          "fecha": "2026-09-16",
          "actividad": "Desarrollo",
          "hTrad": "",
          "hIA": "7.5",
          "validacion": "CI 11/11 verde · 13+5 archivos de test · OpenSpec retire-deployed-agents",
          "validado": true,
          "evidencia": "https://github.com/CHidalgo29/AgentPlatform/pull/437"
        },
        {
          "id": "c402",
          "caso": "Candidato extra: Funciones de transformación de campos en tool wizard (#402, #410)",
          "fecha": "2026-09-11",
          "actividad": "Desarrollo",
          "hTrad": "",
          "hIA": "7.3",
          "validacion": "CI 11/11 verde · 85+10 archivos de test · OpenSpec add-tool-field-transformations",
          "validado": true,
          "evidencia": "https://github.com/CHidalgo29/AgentPlatform/pull/402"
        },
        {
          "id": "c423",
          "caso": "Candidato extra: Mantenimiento de knowledge base: editar, reemplazar documentos (#423)",
          "fecha": "2026-09-14",
          "actividad": "Desarrollo",
          "hTrad": "",
          "hIA": "11.5",
          "validacion": "CI 11/11 verde · 17 archivos de test · OpenSpec add-knowledge-base-maintenance",
          "validado": true,
          "evidencia": "https://github.com/CHidalgo29/AgentPlatform/pull/423"
        }
      ],
      "evidence": [
        {
          "id": "e1",
          "title": "Resumen de uso de IA en AgentPlatform",
          "url": "evidencias/o1-ai-first/uso-habitual-ia.md",
          "date": "2026-09-28"
        },
        {
          "id": "e3",
          "title": "Comparación 3x: SiGes (tradicional) vs AgentPlatform (IA)",
          "url": "evidencias/o1-ai-first/comparacion-3x.md",
          "date": "2026-09-28"
        },
        {
          "id": "e2",
          "title": "Script de medición de tiempo con IA",
          "url": "scripts/medir-tiempo-ia.py",
          "date": "2026-09-28"
        }
      ],
      "notes": "Tradicional = campo Duración final de Jira SIGE (Portal del Colaborador y SiGes V2, jul–nov 2025).\nCon IA = tiempo activo de sesiones de Claude Code en la rama (pausas >30 min excluidas), medido con scripts/medir-tiempo-ia.py.\nPendiente: visto bueno del líder técnico sobre la comparabilidad de los pares y capturas de Jira."
    },
    "o2": {
      "override": {
        "done": false,
        "note": "",
        "date": ""
      },
      "notes": "Promedio enero–agosto 2026: 94.0% productivo (equipo SWAT: 91.3%). Meta ≥70%.\nPendiente: agregar septiembre en adelante cuando se publique.",
      "rows": [
        {
          "id": "m1",
          "mes": "2026-01",
          "pct": "100",
          "fuente": "Indicadores CH (SWAT) · equipo 92%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        },
        {
          "id": "m2",
          "mes": "2026-02",
          "pct": "94",
          "fuente": "Indicadores CH (SWAT) · equipo 93%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        },
        {
          "id": "m3",
          "mes": "2026-03",
          "pct": "92",
          "fuente": "Indicadores CH (SWAT) · equipo 93%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        },
        {
          "id": "m4",
          "mes": "2026-04",
          "pct": "93",
          "fuente": "Indicadores CH (SWAT) · equipo 91%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        },
        {
          "id": "m5",
          "mes": "2026-05",
          "pct": "95",
          "fuente": "Indicadores CH (SWAT) · equipo 91%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        },
        {
          "id": "m6",
          "mes": "2026-06",
          "pct": "91",
          "fuente": "Indicadores CH (SWAT) · equipo 88%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        },
        {
          "id": "m7",
          "mes": "2026-07",
          "pct": "92",
          "fuente": "Indicadores CH (SWAT) · equipo 91%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        },
        {
          "id": "m8",
          "mes": "2026-08",
          "pct": "95",
          "fuente": "Indicadores CH (SWAT) · equipo 91%",
          "evidencia": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH"
        }
      ],
      "checks": {
        "fuente": {
          "done": true,
          "date": "2026-09-28",
          "link": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH",
          "note": "Confluence SWAT · Indicadores CH (extracto Horas Carlos de Indicadores 2026)"
        },
        "mensual": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o2-tiempo-productivo/indicadores-2026.md",
          "note": "Enero a agosto 2026 registrados; agregar cada mes nuevo"
        },
        "ajuste": {
          "done": true,
          "date": "2026-09-28",
          "link": "evidencias/o2-tiempo-productivo/indicadores-2026.md",
          "note": "Ningún mes bajo 70%; mínimo 91% (junio)"
        }
      },
      "evidence": [
        {
          "id": "e1",
          "title": "Indicadores CH (Confluence SWAT)",
          "url": "https://soinlabs.atlassian.net/wiki/spaces/SWAT/pages/997326851/Indicadores+CH",
          "date": "2026-09-28"
        },
        {
          "id": "e2",
          "title": "Resumen del registro oficial 2026",
          "url": "evidencias/o2-tiempo-productivo/indicadores-2026.md",
          "date": "2026-09-28"
        }
      ]
    }
  }
};
